//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPaqueteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios
    {
        public int iIdUsuario { get; set; }
        public string cUsuario { get; set; }
        public string cPassword { get; set; }
        public string cNombre { get; set; }
        public int iNivel { get; set; }
        public string cSucursal { get; set; }
    }
}
